### ISSUE TITLE
flash message 'This sensor ID is already registered.' istn't translated by babel

### ISSUE THREAD

**Issue by ricki-z** [opendata-stuttgart/devices.sensor.community#22]

**Comment by ricki-z** [comment]
There are some more places where the translation doesn't work, i.e. "Email Address" and "Password" on the user registration page.

**Comment by Informatic** [comment]
Can't this be translated via `flask_security.po` file in `translations/*`? (didn't check this yet, just asking if anyone tried this)

**Comment by ricki-z** [comment]
if i "compile" the flask_security.po file then the text is translated. Is there any reason for a second.mo file?

**Comment by Informatic** [comment]
Yes. The idea here is that this is flask-security module translations. In theory we should be able to just pull these from https://github.com/mattupstate/flask-security/tree/develop/flask_security/translations (and also contribute our translations when appropriate) In theory these should be automatically loaded, but *something* is broken in our codebase (presumably a conflict between Flask-Babel used by wtforms or some other module and Flask-BabelEx used by Flask-Security...) so that we need to have these "external" translations pulled into our local `translations/` directory. I've spent some time trying to debug this original issue, but couldn't figure it out without forking either of these projects... :/
